/* Generated By:JavaCC: Do not edit this line. ContextRuleParserConstants.java */
package at.fhooe.mc.lbcas.contextrulejavacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ContextRuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GREATER = 5;
  /** RegularExpression Id. */
  int LESS = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int NOTEQUAL = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int POSITION_NOW = 11;
  /** RegularExpression Id. */
  int DAYNIGHT_MODE = 12;
  /** RegularExpression Id. */
  int USER_MODE = 13;
  /** RegularExpression Id. */
  int TIME_NOW = 14;
  /** RegularExpression Id. */
  int TEMPERATURE_NOW = 15;
  /** RegularExpression Id. */
  int UNIVERSITY_CAMPUS = 16;
  /** RegularExpression Id. */
  int DAY = 17;
  /** RegularExpression Id. */
  int NIGHT = 18;
  /** RegularExpression Id. */
  int DRIVING = 19;
  /** RegularExpression Id. */
  int WALKING = 20;
  /** RegularExpression Id. */
  int AM = 21;
  /** RegularExpression Id. */
  int PM = 22;
  /** RegularExpression Id. */
  int DECIMAL = 23;
  /** RegularExpression Id. */
  int NUMBERZERO = 24;
  /** RegularExpression Id. */
  int NUMBERONE = 25;
  /** RegularExpression Id. */
  int NUMBERTWO = 26;
  /** RegularExpression Id. */
  int NUMBERTHREE = 27;
  /** RegularExpression Id. */
  int NUMBERFOUR = 28;
  /** RegularExpression Id. */
  int NUMBERFIVE = 29;
  /** RegularExpression Id. */
  int NUMBERSIX = 30;
  /** RegularExpression Id. */
  int NUMBERSEVEN = 31;
  /** RegularExpression Id. */
  int NUMBEREIGHT = 32;
  /** RegularExpression Id. */
  int NUMBERNINE = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"position_now\"",
    "\"daynight_mode\"",
    "\"user_mode\"",
    "\"time_now\"",
    "\"temperature_now\"",
    "\"UNIVERSITY_CAMPUS\"",
    "\"DAY\"",
    "\"NIGHT\"",
    "\"DRIVING\"",
    "\"WALKING\"",
    "\"AM\"",
    "\"PM\"",
    "\"DECIMAL\"",
    "<NUMBERZERO>",
    "<NUMBERONE>",
    "<NUMBERTWO>",
    "<NUMBERTHREE>",
    "<NUMBERFOUR>",
    "<NUMBERFIVE>",
    "<NUMBERSIX>",
    "<NUMBERSEVEN>",
    "<NUMBEREIGHT>",
    "<NUMBERNINE>",
  };

}
