/* Generated By:JavaCC: Do not edit this line. ContextRuleParserConstants.java */
package at.fhooe.mc.lbcas.contextrulejavacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ContextRuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GREATER = 5;
  /** RegularExpression Id. */
  int LESS = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int NOTEQUAL = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int OPENING_BRACKET = 11;
  /** RegularExpression Id. */
  int CLOSING_BRACKET = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int POSITION_NOW = 14;
  /** RegularExpression Id. */
  int DAYNIGHT_MODE = 15;
  /** RegularExpression Id. */
  int LANGUAGE_MODE = 16;
  /** RegularExpression Id. */
  int TIME_NOW = 17;
  /** RegularExpression Id. */
  int TEMPERATURE_NOW = 18;
  /** RegularExpression Id. */
  int UNIVERSITY_CAMPUS = 19;
  /** RegularExpression Id. */
  int DAY = 20;
  /** RegularExpression Id. */
  int NIGHT = 21;
  /** RegularExpression Id. */
  int ENGLISH = 22;
  /** RegularExpression Id. */
  int GERMAN = 23;
  /** RegularExpression Id. */
  int AM = 24;
  /** RegularExpression Id. */
  int PM = 25;
  /** RegularExpression Id. */
  int DECIMAL = 26;
  /** RegularExpression Id. */
  int TIMECONSTANT = 27;
  /** RegularExpression Id. */
  int TEMPERATURECONSTANT = 28;
  /** RegularExpression Id. */
  int NUMBERZERO = 29;
  /** RegularExpression Id. */
  int NUMBERONE = 30;
  /** RegularExpression Id. */
  int NUMBERTWO = 31;
  /** RegularExpression Id. */
  int NUMBERTHREE = 32;
  /** RegularExpression Id. */
  int NUMBERFOUR = 33;
  /** RegularExpression Id. */
  int NUMBERFIVE = 34;
  /** RegularExpression Id. */
  int NUMBERSIX = 35;
  /** RegularExpression Id. */
  int NUMBERSEVEN = 36;
  /** RegularExpression Id. */
  int NUMBEREIGHT = 37;
  /** RegularExpression Id. */
  int NUMBERNINE = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"position_now\"",
    "\"daynight_mode\"",
    "\"language_mode\"",
    "\"time_now\"",
    "\"temperature_now\"",
    "\"UNIVERSITY_CAMPUS\"",
    "\"DAY\"",
    "\"NIGHT\"",
    "\"ENGLISH\"",
    "\"GERMAN\"",
    "\"AM\"",
    "\"PM\"",
    "\"DECIMAL\"",
    "<TIMECONSTANT>",
    "<TEMPERATURECONSTANT>",
    "<NUMBERZERO>",
    "<NUMBERONE>",
    "<NUMBERTWO>",
    "<NUMBERTHREE>",
    "<NUMBERFOUR>",
    "<NUMBERFIVE>",
    "<NUMBERSIX>",
    "<NUMBERSEVEN>",
    "<NUMBEREIGHT>",
    "<NUMBERNINE>",
  };

}
