/*
 * BackgroundPanel.java
 *
 * Created on April 6, 2011, 10:50 PM
 */
package salesmanagement;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.IOException;

/**
 * 
 * @author Aparna
 */
public class BackgroundPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Image image;

	/** Creates new form BackgroundPanel */
	public BackgroundPanel() {
		BufferedInputStream imgStream = new BufferedInputStream(getClass()
				.getClassLoader().getResourceAsStream("grid_updated.jpg"));
		// int count = 0;
		byte buf[] = new byte[75000];
		if (imgStream != null) {
			try {
				imgStream.read(buf);
				imgStream.close();
			} catch (IOException ieo) {
				System.err.println("Couldn't read stream from file: "
						+ ieo.getMessage());
			}
		}

		this.image = Toolkit.getDefaultToolkit().createImage(buf);
		Dimension size = new Dimension(image.getWidth(null),
				image.getHeight(null));
		setPreferredSize(size);
		setMinimumSize(size);
		setMaximumSize(size);
		setSize(size);
		setLayout(null);
		initComponents();
	}

	@Override
	public void paintComponent(Graphics g) {
		g.drawImage(image, 29, 37, null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setName("Form"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables
		// End of variables declaration//GEN-END:variables
}
