/* Generated By:JavaCC: Do not edit this line. NMEAProtocolParserTokenManager.java */
package at.fhooe.mc.lbcas.nmeaprotocoljavacc;

/** Token Manager. */
public class NMEAProtocolParserTokenManager implements NMEAProtocolParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 36:
         return jjStopAtPos(0, 5);
      case 42:
         return jjStopAtPos(0, 26);
      case 44:
         return jjStopAtPos(0, 27);
      case 46:
         return jjStopAtPos(0, 24);
      case 59:
         return jjStopAtPos(0, 28);
      case 77:
         return jjStopAtPos(0, 25);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 18;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 57)
                  {
                     if (kind > 23)
                        kind = 23;
                  }
                  else if (curChar == 56)
                  {
                     if (kind > 22)
                        kind = 22;
                  }
                  else if (curChar == 55)
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  else if (curChar == 54)
                  {
                     if (kind > 20)
                        kind = 20;
                  }
                  else if (curChar == 53)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  else if (curChar == 52)
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  else if (curChar == 51)
                  {
                     if (kind > 17)
                        kind = 17;
                  }
                  else if (curChar == 50)
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  else if (curChar == 49)
                  {
                     if (kind > 15)
                        kind = 15;
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 14)
                        kind = 14;
                  }
                  break;
               case 8:
                  if (curChar == 48)
                     kind = 14;
                  break;
               case 9:
                  if (curChar == 49)
                     kind = 15;
                  break;
               case 10:
                  if (curChar == 50)
                     kind = 16;
                  break;
               case 11:
                  if (curChar == 51)
                     kind = 17;
                  break;
               case 12:
                  if (curChar == 52)
                     kind = 18;
                  break;
               case 13:
                  if (curChar == 53)
                     kind = 19;
                  break;
               case 14:
                  if (curChar == 54)
                     kind = 20;
                  break;
               case 15:
                  if (curChar == 55)
                     kind = 21;
                  break;
               case 16:
                  if (curChar == 56)
                     kind = 22;
                  break;
               case 17:
                  if (curChar == 57)
                     kind = 23;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x10082L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 69)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  else if (curChar == 83)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  else if (curChar == 87)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  else if (curChar == 78)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  if (curChar == 65)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 80)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if (curChar == 71)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  break;
               case 1:
                  if (curChar == 80 && kind > 7)
                     kind = 7;
                  break;
               case 2:
                  if (curChar == 65 && kind > 8)
                     kind = 8;
                  break;
               case 3:
                  if (curChar == 78)
                     kind = 9;
                  break;
               case 4:
                  if (curChar == 87)
                     kind = 10;
                  break;
               case 5:
                  if (curChar == 83)
                     kind = 11;
                  break;
               case 6:
                  if (curChar == 69)
                     kind = 12;
                  break;
               case 7:
                  if ((0x10082L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 18 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\44", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, "\56", "\115", 
"\52", "\54", "\73", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1fffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[18];
static private final int[] jjstateSet = new int[36];
static protected char curChar;
/** Constructor. */
public NMEAProtocolParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public NMEAProtocolParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 18; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
