/* Generated By:JavaCC: Do not edit this line. NMEAProtocolParserConstants.java */
package at.fhooe.mc.lbcas.nmeaprotocoljavacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NMEAProtocolParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int CARRIAGERETURN = 2;
  /** RegularExpression Id. */
  int TAB = 3;
  /** RegularExpression Id. */
  int NEWLINE = 4;
  /** RegularExpression Id. */
  int DOLLAR = 5;
  /** RegularExpression Id. */
  int GTOKEN = 6;
  /** RegularExpression Id. */
  int PTOKEN = 7;
  /** RegularExpression Id. */
  int ATOKEN = 8;
  /** RegularExpression Id. */
  int NTOKEN = 9;
  /** RegularExpression Id. */
  int WTOKEN = 10;
  /** RegularExpression Id. */
  int STOKEN = 11;
  /** RegularExpression Id. */
  int ETOKEN = 12;
  /** RegularExpression Id. */
  int SENTENCEIDENTIFIER = 13;
  /** RegularExpression Id. */
  int NUMBERZERO = 14;
  /** RegularExpression Id. */
  int NUMBERONE = 15;
  /** RegularExpression Id. */
  int NUMBERTWO = 16;
  /** RegularExpression Id. */
  int NUMBERTHREE = 17;
  /** RegularExpression Id. */
  int NUMBERFOUR = 18;
  /** RegularExpression Id. */
  int NUMBERFIVE = 19;
  /** RegularExpression Id. */
  int NUMBERSIX = 20;
  /** RegularExpression Id. */
  int NUMBERSEVEN = 21;
  /** RegularExpression Id. */
  int NUMBEREIGHT = 22;
  /** RegularExpression Id. */
  int NUMBERNINE = 23;
  /** RegularExpression Id. */
  int DECIMAL = 24;
  /** RegularExpression Id. */
  int METER = 25;
  /** RegularExpression Id. */
  int STAR = 26;
  /** RegularExpression Id. */
  int COMMA = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"$\"",
    "<GTOKEN>",
    "<PTOKEN>",
    "<ATOKEN>",
    "<NTOKEN>",
    "<WTOKEN>",
    "<STOKEN>",
    "<ETOKEN>",
    "<SENTENCEIDENTIFIER>",
    "<NUMBERZERO>",
    "<NUMBERONE>",
    "<NUMBERTWO>",
    "<NUMBERTHREE>",
    "<NUMBERFOUR>",
    "<NUMBERFIVE>",
    "<NUMBERSIX>",
    "<NUMBERSEVEN>",
    "<NUMBEREIGHT>",
    "<NUMBERNINE>",
    "\".\"",
    "\"M\"",
    "\"*\"",
    "\",\"",
    "\";\"",
  };

}
