//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.03 at 03:35:30 PM CET 
//

package com.context.data.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocationContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="PhysicalLocation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pincode" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="GeographicalLocation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="Altitude" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Place">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="indoor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="outdoor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeviceContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Device">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Memory" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Display" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Audio" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="BatteryPercentage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Software">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="operatingsystem" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TimeContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Date">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Time">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Hour" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Minutes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Seconds" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Miliseconds" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="AMPM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SocialContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PhysicalContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UserContextElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="UserProfile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Age" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Health">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="BloodPressure" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="HeartRate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="VoiceTone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="contexttype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "locationContextElement",
		"deviceContextElement", "timeContextElement", "socialContextElement",
		"physicalContextElement", "userContextElement" })
@XmlRootElement(name = "ContextElement")
public class ContextElement {

	@XmlElement(name = "LocationContextElement")
	protected ContextElement.LocationContextElement locationContextElement;
	@XmlElement(name = "DeviceContextElement")
	protected ContextElement.DeviceContextElement deviceContextElement;
	@XmlElement(name = "TimeContextElement")
	protected ContextElement.TimeContextElement timeContextElement;
	@XmlElement(name = "SocialContextElement")
	protected ContextElement.SocialContextElement socialContextElement;
	@XmlElement(name = "PhysicalContextElement")
	protected ContextElement.PhysicalContextElement physicalContextElement;
	@XmlElement(name = "UserContextElement")
	protected ContextElement.UserContextElement userContextElement;
	@XmlAttribute(name = "contexttype", required = true)
	protected String contexttype;

	/**
	 * Gets the value of the locationContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.LocationContextElement }
	 * 
	 */
	public ContextElement.LocationContextElement getLocationContextElement() {
		return locationContextElement;
	}

	/**
	 * Sets the value of the locationContextElement property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link ContextElement.LocationContextElement }
	 * 
	 */
	public void setLocationContextElement(
			ContextElement.LocationContextElement value) {
		this.locationContextElement = value;
	}

	/**
	 * Gets the value of the deviceContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.DeviceContextElement }
	 * 
	 */
	public ContextElement.DeviceContextElement getDeviceContextElement() {
		return deviceContextElement;
	}

	/**
	 * Sets the value of the deviceContextElement property.
	 * 
	 * @param value
	 *            allowed object is {@link ContextElement.DeviceContextElement }
	 * 
	 */
	public void setDeviceContextElement(
			ContextElement.DeviceContextElement value) {
		this.deviceContextElement = value;
	}

	/**
	 * Gets the value of the timeContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.TimeContextElement }
	 * 
	 */
	public ContextElement.TimeContextElement getTimeContextElement() {
		return timeContextElement;
	}

	/**
	 * Sets the value of the timeContextElement property.
	 * 
	 * @param value
	 *            allowed object is {@link ContextElement.TimeContextElement }
	 * 
	 */
	public void setTimeContextElement(ContextElement.TimeContextElement value) {
		this.timeContextElement = value;
	}

	/**
	 * Gets the value of the socialContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.SocialContextElement }
	 * 
	 */
	public ContextElement.SocialContextElement getSocialContextElement() {
		return socialContextElement;
	}

	/**
	 * Sets the value of the socialContextElement property.
	 * 
	 * @param value
	 *            allowed object is {@link ContextElement.SocialContextElement }
	 * 
	 */
	public void setSocialContextElement(
			ContextElement.SocialContextElement value) {
		this.socialContextElement = value;
	}

	/**
	 * Gets the value of the physicalContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.PhysicalContextElement }
	 * 
	 */
	public ContextElement.PhysicalContextElement getPhysicalContextElement() {
		return physicalContextElement;
	}

	/**
	 * Sets the value of the physicalContextElement property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link ContextElement.PhysicalContextElement }
	 * 
	 */
	public void setPhysicalContextElement(
			ContextElement.PhysicalContextElement value) {
		this.physicalContextElement = value;
	}

	/**
	 * Gets the value of the userContextElement property.
	 * 
	 * @return possible object is {@link ContextElement.UserContextElement }
	 * 
	 */
	public ContextElement.UserContextElement getUserContextElement() {
		return userContextElement;
	}

	/**
	 * Sets the value of the userContextElement property.
	 * 
	 * @param value
	 *            allowed object is {@link ContextElement.UserContextElement }
	 * 
	 */
	public void setUserContextElement(ContextElement.UserContextElement value) {
		this.userContextElement = value;
	}

	/**
	 * Gets the value of the contexttype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContexttype() {
		return contexttype;
	}

	/**
	 * Sets the value of the contexttype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContexttype(String value) {
		this.contexttype = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;all>
	 *         &lt;element name="Device">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Memory" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Display" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Audio" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *                 &lt;attribute name="BatteryPercentage" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Software">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="operatingsystem" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/all>
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class DeviceContextElement {

		@XmlElement(name = "Device", required = true)
		protected ContextElement.DeviceContextElement.Device device;
		@XmlElement(name = "Software", required = true)
		protected ContextElement.DeviceContextElement.Software software;
		@XmlAttribute(name = "contextid")
		protected Integer contextid;

		/**
		 * Gets the value of the device property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.DeviceContextElement.Device }
		 * 
		 */
		public ContextElement.DeviceContextElement.Device getDevice() {
			return device;
		}

		/**
		 * Sets the value of the device property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.DeviceContextElement.Device }
		 * 
		 */
		public void setDevice(ContextElement.DeviceContextElement.Device value) {
			this.device = value;
		}

		/**
		 * Gets the value of the software property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.DeviceContextElement.Software }
		 * 
		 */
		public ContextElement.DeviceContextElement.Software getSoftware() {
			return software;
		}

		/**
		 * Sets the value of the software property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.DeviceContextElement.Software }
		 * 
		 */
		public void setSoftware(
				ContextElement.DeviceContextElement.Software value) {
			this.software = value;
		}

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setContextid(Integer value) {
			this.contextid = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Memory" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Display" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Audio" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *       &lt;attribute name="BatteryPercentage" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Device {

			@XmlAttribute(name = "Memory")
			protected Integer memory;
			@XmlAttribute(name = "Display")
			protected String display;
			@XmlAttribute(name = "Audio")
			protected Boolean audio;
			@XmlAttribute(name = "BatteryPercentage")
			protected Integer batteryPercentage;

			/**
			 * Gets the value of the memory property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getMemory() {
				return memory;
			}

			/**
			 * Sets the value of the memory property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setMemory(Integer value) {
				this.memory = value;
			}

			/**
			 * Gets the value of the display property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDisplay() {
				return display;
			}

			/**
			 * Sets the value of the display property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDisplay(String value) {
				this.display = value;
			}

			/**
			 * Gets the value of the audio property.
			 * 
			 * @return possible object is {@link Boolean }
			 * 
			 */
			public Boolean isAudio() {
				return audio;
			}

			/**
			 * Sets the value of the audio property.
			 * 
			 * @param value
			 *            allowed object is {@link Boolean }
			 * 
			 */
			public void setAudio(Boolean value) {
				this.audio = value;
			}

			/**
			 * Gets the value of the batteryPercentage property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getBatteryPercentage() {
				return batteryPercentage;
			}

			/**
			 * Sets the value of the batteryPercentage property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setBatteryPercentage(Integer value) {
				this.batteryPercentage = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="operatingsystem" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Software {

			@XmlAttribute(name = "operatingsystem")
			protected String operatingsystem;
			@XmlAttribute(name = "version")
			protected Float version;

			/**
			 * Gets the value of the operatingsystem property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOperatingsystem() {
				return operatingsystem;
			}

			/**
			 * Sets the value of the operatingsystem property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOperatingsystem(String value) {
				this.operatingsystem = value;
			}

			/**
			 * Gets the value of the version property.
			 * 
			 * @return possible object is {@link Float }
			 * 
			 */
			public Float getVersion() {
				return version;
			}

			/**
			 * Sets the value of the version property.
			 * 
			 * @param value
			 *            allowed object is {@link Float }
			 * 
			 */
			public void setVersion(Float value) {
				this.version = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;all>
	 *         &lt;element name="PhysicalLocation">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="pincode" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="GeographicalLocation">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *                 &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *                 &lt;attribute name="Altitude" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Place">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="indoor" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="outdoor" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/all>
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class LocationContextElement {

		@XmlElement(name = "PhysicalLocation", required = true)
		protected ContextElement.LocationContextElement.PhysicalLocation physicalLocation;
		@XmlElement(name = "GeographicalLocation", required = true)
		protected ContextElement.LocationContextElement.GeographicalLocation geographicalLocation;
		@XmlElement(name = "Place", required = true)
		protected ContextElement.LocationContextElement.Place place;
		@XmlAttribute(name = "contextid")
		protected Integer contextid;

		/**
		 * Gets the value of the physicalLocation property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.LocationContextElement.PhysicalLocation }
		 * 
		 */
		public ContextElement.LocationContextElement.PhysicalLocation getPhysicalLocation() {
			return physicalLocation;
		}

		/**
		 * Sets the value of the physicalLocation property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.LocationContextElement.PhysicalLocation }
		 * 
		 */
		public void setPhysicalLocation(
				ContextElement.LocationContextElement.PhysicalLocation value) {
			this.physicalLocation = value;
		}

		/**
		 * Gets the value of the geographicalLocation property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.LocationContextElement.GeographicalLocation }
		 * 
		 */
		public ContextElement.LocationContextElement.GeographicalLocation getGeographicalLocation() {
			return geographicalLocation;
		}

		/**
		 * Sets the value of the geographicalLocation property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.LocationContextElement.GeographicalLocation }
		 * 
		 */
		public void setGeographicalLocation(
				ContextElement.LocationContextElement.GeographicalLocation value) {
			this.geographicalLocation = value;
		}

		/**
		 * Gets the value of the place property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.LocationContextElement.Place }
		 * 
		 */
		public ContextElement.LocationContextElement.Place getPlace() {
			return place;
		}

		/**
		 * Sets the value of the place property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.LocationContextElement.Place }
		 * 
		 */
		public void setPlace(ContextElement.LocationContextElement.Place value) {
			this.place = value;
		}

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setContextid(Integer value) {
			this.contextid = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" />
		 *       &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" />
		 *       &lt;attribute name="Altitude" type="{http://www.w3.org/2001/XMLSchema}float" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class GeographicalLocation {

			@XmlAttribute(name = "Latitude")
			protected double latitude;
			@XmlAttribute(name = "Longitude")
			protected double longitude;
			@XmlAttribute(name = "Altitude")
			protected Float altitude;

			/**
			 * Gets the value of the latitude property.
			 * 
			 * @return possible object is {@link Float }
			 * 
			 */
			public double getLatitude() {
				return latitude;
			}

			/**
			 * Sets the value of the latitude property.
			 * 
			 * @param d
			 *            allowed object is {@link Float }
			 * 
			 */
			public void setLatitude(double d) {
				this.latitude = d;
			}

			/**
			 * Gets the value of the longitude property.
			 * 
			 * @return possible object is {@link Float }
			 * 
			 */
			public double getLongitude() {
				return longitude;
			}

			/**
			 * Sets the value of the longitude property.
			 * 
			 * @param d
			 *            allowed object is {@link Float }
			 * 
			 */
			public void setLongitude(double d) {
				this.longitude = d;
			}

			/**
			 * Gets the value of the altitude property.
			 * 
			 * @return possible object is {@link Float }
			 * 
			 */
			public Float getAltitude() {
				return altitude;
			}

			/**
			 * Sets the value of the altitude property.
			 * 
			 * @param value
			 *            allowed object is {@link Float }
			 * 
			 */
			public void setAltitude(Float value) {
				this.altitude = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="pincode" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class PhysicalLocation {

			@XmlAttribute(name = "country")
			protected String country;
			@XmlAttribute(name = "state")
			protected String state;
			@XmlAttribute(name = "city")
			protected String city;
			@XmlAttribute(name = "pincode")
			protected Integer pincode;

			/**
			 * Gets the value of the country property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountry() {
				return country;
			}

			/**
			 * Sets the value of the country property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountry(String value) {
				this.country = value;
			}

			/**
			 * Gets the value of the state property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getState() {
				return state;
			}

			/**
			 * Sets the value of the state property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setState(String value) {
				this.state = value;
			}

			/**
			 * Gets the value of the city property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCity() {
				return city;
			}

			/**
			 * Sets the value of the city property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCity(String value) {
				this.city = value;
			}

			/**
			 * Gets the value of the pincode property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getPincode() {
				return pincode;
			}

			/**
			 * Sets the value of the pincode property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setPincode(Integer value) {
				this.pincode = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="indoor" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="outdoor" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Place {

			@XmlAttribute(name = "indoor")
			protected String indoor;
			@XmlAttribute(name = "outdoor")
			protected String outdoor;

			/**
			 * Gets the value of the indoor property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getIndoor() {
				return indoor;
			}

			/**
			 * Sets the value of the indoor property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setIndoor(String value) {
				this.indoor = value;
			}

			/**
			 * Gets the value of the outdoor property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOutdoor() {
				return outdoor;
			}

			/**
			 * Sets the value of the outdoor property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOutdoor(String value) {
				this.outdoor = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class PhysicalContextElement {

		@XmlAttribute(name = "contextid")
		@XmlSchemaType(name = "anySimpleType")
		protected String contextid;

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setContextid(String value) {
			this.contextid = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class SocialContextElement {

		@XmlAttribute(name = "contextid")
		@XmlSchemaType(name = "anySimpleType")
		protected String contextid;

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setContextid(String value) {
			this.contextid = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;all>
	 *         &lt;element name="Date">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Time">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Hour" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Minutes" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Seconds" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Miliseconds" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="AMPM" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/all>
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class TimeContextElement {

		@XmlElement(name = "Date", required = true)
		protected ContextElement.TimeContextElement.Date date;
		@XmlElement(name = "Time", required = true)
		protected ContextElement.TimeContextElement.Time time;
		@XmlAttribute(name = "contextid")
		protected Integer contextid;

		/**
		 * Gets the value of the date property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.TimeContextElement.Date }
		 * 
		 */
		public ContextElement.TimeContextElement.Date getDate() {
			return date;
		}

		/**
		 * Sets the value of the date property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.TimeContextElement.Date }
		 * 
		 */
		public void setDate(ContextElement.TimeContextElement.Date value) {
			this.date = value;
		}

		/**
		 * Gets the value of the time property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.TimeContextElement.Time }
		 * 
		 */
		public ContextElement.TimeContextElement.Time getTime() {
			return time;
		}

		/**
		 * Sets the value of the time property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.TimeContextElement.Time }
		 * 
		 */
		public void setTime(ContextElement.TimeContextElement.Time value) {
			this.time = value;
		}

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setContextid(Integer value) {
			this.contextid = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Date {

			@XmlAttribute(name = "Year")
			protected Integer year;
			@XmlAttribute(name = "Month")
			protected Integer month;
			@XmlAttribute(name = "Day")
			protected Integer day;

			/**
			 * Gets the value of the year property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getYear() {
				return year;
			}

			/**
			 * Sets the value of the year property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setYear(Integer value) {
				this.year = value;
			}

			/**
			 * Gets the value of the month property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getMonth() {
				return month;
			}

			/**
			 * Sets the value of the month property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setMonth(Integer value) {
				this.month = value;
			}

			/**
			 * Gets the value of the day property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getDay() {
				return day;
			}

			/**
			 * Sets the value of the day property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setDay(Integer value) {
				this.day = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Hour" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Minutes" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Seconds" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Miliseconds" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="AMPM" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Time {

			@XmlAttribute(name = "Hour")
			protected Integer hour;
			@XmlAttribute(name = "Minutes")
			protected Integer minutes;
			@XmlAttribute(name = "Seconds")
			protected Integer seconds;
			@XmlAttribute(name = "Miliseconds")
			protected Integer miliseconds;
			@XmlAttribute(name = "AMPM")
			protected String ampm;
			@XmlAttribute(name = "TimeZone")
			protected String timeZone;

			/**
			 * Gets the value of the hour property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getHour() {
				return hour;
			}

			/**
			 * Sets the value of the hour property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setHour(Integer value) {
				this.hour = value;
			}

			/**
			 * Gets the value of the minutes property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getMinutes() {
				return minutes;
			}

			/**
			 * Sets the value of the minutes property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setMinutes(Integer value) {
				this.minutes = value;
			}

			/**
			 * Gets the value of the seconds property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getSeconds() {
				return seconds;
			}

			/**
			 * Sets the value of the seconds property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setSeconds(Integer value) {
				this.seconds = value;
			}

			/**
			 * Gets the value of the miliseconds property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getMiliseconds() {
				return miliseconds;
			}

			/**
			 * Sets the value of the miliseconds property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setMiliseconds(Integer value) {
				this.miliseconds = value;
			}

			/**
			 * Gets the value of the ampm property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAMPM() {
				return ampm;
			}

			/**
			 * Sets the value of the ampm property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAMPM(String value) {
				this.ampm = value;
			}

			/**
			 * Gets the value of the timeZone property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTimeZone() {
				return timeZone;
			}

			/**
			 * Sets the value of the timeZone property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTimeZone(String value) {
				this.timeZone = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;all>
	 *         &lt;element name="UserProfile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Age" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Health">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="BloodPressure" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="HeartRate" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="Disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *                 &lt;attribute name="VoiceTone" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/all>
	 *       &lt;attribute name="contextid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class UserContextElement {

		@XmlElement(name = "UserProfile", required = true)
		protected ContextElement.UserContextElement.UserProfile userProfile;
		@XmlElement(name = "Health", required = true)
		protected ContextElement.UserContextElement.Health health;
		@XmlAttribute(name = "contextid")
		@XmlSchemaType(name = "anySimpleType")
		protected String contextid;

		/**
		 * Gets the value of the userProfile property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.UserContextElement.UserProfile }
		 * 
		 */
		public ContextElement.UserContextElement.UserProfile getUserProfile() {
			return userProfile;
		}

		/**
		 * Sets the value of the userProfile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.UserContextElement.UserProfile }
		 * 
		 */
		public void setUserProfile(
				ContextElement.UserContextElement.UserProfile value) {
			this.userProfile = value;
		}

		/**
		 * Gets the value of the health property.
		 * 
		 * @return possible object is
		 *         {@link ContextElement.UserContextElement.Health }
		 * 
		 */
		public ContextElement.UserContextElement.Health getHealth() {
			return health;
		}

		/**
		 * Sets the value of the health property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContextElement.UserContextElement.Health }
		 * 
		 */
		public void setHealth(ContextElement.UserContextElement.Health value) {
			this.health = value;
		}

		/**
		 * Gets the value of the contextid property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getContextid() {
			return contextid;
		}

		/**
		 * Sets the value of the contextid property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setContextid(String value) {
			this.contextid = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="BloodPressure" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="HeartRate" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *       &lt;attribute name="VoiceTone" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Health {

			@XmlAttribute(name = "BloodPressure")
			protected String bloodPressure;
			@XmlAttribute(name = "HeartRate")
			protected String heartRate;
			@XmlAttribute(name = "Disabled")
			protected Boolean disabled;
			@XmlAttribute(name = "VoiceTone")
			protected String voiceTone;

			/**
			 * Gets the value of the bloodPressure property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBloodPressure() {
				return bloodPressure;
			}

			/**
			 * Sets the value of the bloodPressure property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBloodPressure(String value) {
				this.bloodPressure = value;
			}

			/**
			 * Gets the value of the heartRate property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getHeartRate() {
				return heartRate;
			}

			/**
			 * Sets the value of the heartRate property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setHeartRate(String value) {
				this.heartRate = value;
			}

			/**
			 * Gets the value of the disabled property.
			 * 
			 * @return possible object is {@link Boolean }
			 * 
			 */
			public Boolean isDisabled() {
				return disabled;
			}

			/**
			 * Sets the value of the disabled property.
			 * 
			 * @param value
			 *            allowed object is {@link Boolean }
			 * 
			 */
			public void setDisabled(Boolean value) {
				this.disabled = value;
			}

			/**
			 * Gets the value of the voiceTone property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVoiceTone() {
				return voiceTone;
			}

			/**
			 * Sets the value of the voiceTone property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVoiceTone(String value) {
				this.voiceTone = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Age" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class UserProfile {

			@XmlAttribute(name = "Age")
			protected Integer age;
			@XmlAttribute(name = "Sex")
			protected String sex;
			@XmlAttribute(name = "MaritalStatus")
			protected String maritalStatus;
			@XmlAttribute(name = "Nationality")
			protected String nationality;

			/**
			 * Gets the value of the age property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getAge() {
				return age;
			}

			/**
			 * Sets the value of the age property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setAge(Integer value) {
				this.age = value;
			}

			/**
			 * Gets the value of the sex property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSex() {
				return sex;
			}

			/**
			 * Sets the value of the sex property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSex(String value) {
				this.sex = value;
			}

			/**
			 * Gets the value of the maritalStatus property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMaritalStatus() {
				return maritalStatus;
			}

			/**
			 * Sets the value of the maritalStatus property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMaritalStatus(String value) {
				this.maritalStatus = value;
			}

			/**
			 * Gets the value of the nationality property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getNationality() {
				return nationality;
			}

			/**
			 * Sets the value of the nationality property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setNationality(String value) {
				this.nationality = value;
			}

		}

	}

}
