//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.14 at 01:13:57 AM CET 
//


package at.fhooe.mc.lbcas.component.contextdatamodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.fhooe.mc.lbcas.component.contextdatamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.fhooe.mc.lbcas.component.contextdatamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContextElement }
     * 
     */
    public ContextElement createContextElement() {
        return new ContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.UserContextElement }
     * 
     */
    public ContextElement.UserContextElement createContextElementUserContextElement() {
        return new ContextElement.UserContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.TimeContextElement }
     * 
     */
    public ContextElement.TimeContextElement createContextElementTimeContextElement() {
        return new ContextElement.TimeContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.DeviceContextElement }
     * 
     */
    public ContextElement.DeviceContextElement createContextElementDeviceContextElement() {
        return new ContextElement.DeviceContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.TemperatureContextElement }
     * 
     */
    public ContextElement.TemperatureContextElement createContextElementTemperatureContextElement() {
        return new ContextElement.TemperatureContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.LocationContextElement }
     * 
     */
    public ContextElement.LocationContextElement createContextElementLocationContextElement() {
        return new ContextElement.LocationContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.SocialContextElement }
     * 
     */
    public ContextElement.SocialContextElement createContextElementSocialContextElement() {
        return new ContextElement.SocialContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.PhysicalContextElement }
     * 
     */
    public ContextElement.PhysicalContextElement createContextElementPhysicalContextElement() {
        return new ContextElement.PhysicalContextElement();
    }

    /**
     * Create an instance of {@link ContextElement.UserContextElement.UserProfile }
     * 
     */
    public ContextElement.UserContextElement.UserProfile createContextElementUserContextElementUserProfile() {
        return new ContextElement.UserContextElement.UserProfile();
    }

    /**
     * Create an instance of {@link ContextElement.UserContextElement.Health }
     * 
     */
    public ContextElement.UserContextElement.Health createContextElementUserContextElementHealth() {
        return new ContextElement.UserContextElement.Health();
    }

    /**
     * Create an instance of {@link ContextElement.TimeContextElement.Date }
     * 
     */
    public ContextElement.TimeContextElement.Date createContextElementTimeContextElementDate() {
        return new ContextElement.TimeContextElement.Date();
    }

    /**
     * Create an instance of {@link ContextElement.TimeContextElement.Time }
     * 
     */
    public ContextElement.TimeContextElement.Time createContextElementTimeContextElementTime() {
        return new ContextElement.TimeContextElement.Time();
    }

    /**
     * Create an instance of {@link ContextElement.DeviceContextElement.Device }
     * 
     */
    public ContextElement.DeviceContextElement.Device createContextElementDeviceContextElementDevice() {
        return new ContextElement.DeviceContextElement.Device();
    }

    /**
     * Create an instance of {@link ContextElement.DeviceContextElement.Software }
     * 
     */
    public ContextElement.DeviceContextElement.Software createContextElementDeviceContextElementSoftware() {
        return new ContextElement.DeviceContextElement.Software();
    }

    /**
     * Create an instance of {@link ContextElement.TemperatureContextElement.CurrentTemperature }
     * 
     */
    public ContextElement.TemperatureContextElement.CurrentTemperature createContextElementTemperatureContextElementCurrentTemperature() {
        return new ContextElement.TemperatureContextElement.CurrentTemperature();
    }

    /**
     * Create an instance of {@link ContextElement.LocationContextElement.PhysicalLocation }
     * 
     */
    public ContextElement.LocationContextElement.PhysicalLocation createContextElementLocationContextElementPhysicalLocation() {
        return new ContextElement.LocationContextElement.PhysicalLocation();
    }

    /**
     * Create an instance of {@link ContextElement.LocationContextElement.GeographicalLocation }
     * 
     */
    public ContextElement.LocationContextElement.GeographicalLocation createContextElementLocationContextElementGeographicalLocation() {
        return new ContextElement.LocationContextElement.GeographicalLocation();
    }

    /**
     * Create an instance of {@link ContextElement.LocationContextElement.Place }
     * 
     */
    public ContextElement.LocationContextElement.Place createContextElementLocationContextElementPlace() {
        return new ContextElement.LocationContextElement.Place();
    }

}
